### ISSUE TITLE
power of laser

### ISSUE THREAD

**Issue by gimaxy** [RatRig/LaserGRBL#1]
come posso regolare la potenza del laser?

how can i adjust the laser power?

**Comment by RatRig** [comment]
You can adjust the laser power on LaserGRBL software before each cut... 
Its is the M4 (on) and M5(off) gcode command. According to our config file the laser power goes from 0 to 1000, so if you send M4 S1000 (laser at 100%), if you send M4 S555 (laser at 55.5%) and so on... M5 will shutdown the laser
